version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rediscover_postgres
    environment:
      POSTGRES_DB: rediscover
      POSTGRES_USER: rediscover
      POSTGRES_PASSWORD: rediscover
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
